---
# Common tasks for all nodes
- name: Update package cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install common packages
  apt:
    name:
      - nfs-common
      - curl
      - wget
      - vim
      - htop
      - tree
    state: present
  become: true

- name: Create NFS mount point
  file:
    path: "{{ nfs_mount_point }}"
    state: directory
    mode: "0755"
  become: true

- name: Mount NFS share
  mount:
    path: "{{ nfs_mount_point }}"
    src: "{{ filestore_ip }}:/{{ nfs_share_name }}"
    fstype: nfs
    opts: defaults,nolock
    state: mounted
  become: true
  register: nfs_mount_result
  failed_when: false

- name: Create local shared directories if NFS mount failed
  file:
    path: "{{ nfs_mount_point }}/{{ item }}"
    state: directory
    mode: "0755"
  become: true
  loop:
    - scripts
    - configs
    - keys
    - logs
    - slurm-config
  when: nfs_mount_result.failed

- name: Ensure shared directories exist
  file:
    path: "{{ nfs_mount_point }}/{{ item }}"
    state: directory
    mode: "0755"
  become: true
  loop:
    - scripts
    - configs
    - keys
    - logs
    - slurm-config

- name: Set timezone
  timezone:
    name: UTC
  become: true
