---
all:
  children:
    ntt_research:
      children:
        slurm_cluster:
          children:
            slurm_head:
              hosts:
                ntt-research-hpc-slurm-0:
                  ansible_host: "{{ hostvars['ntt-research-hpc-slurm-0']['external_ip'] | default('ntt-research-hpc-slurm-0') }}"
                  slurm_role: controller
                  slurm_node_type: head
            slurm_compute:
              hosts:
                ntt-research-hpc-slurm-1:
                  ansible_host: "{{ hostvars['ntt-research-hpc-slurm-1']['external_ip'] | default('ntt-research-hpc-slurm-1') }}"
                  slurm_role: compute
                  slurm_node_type: compute

        jupyter_nodes:
          hosts:
            ntt-research-jupyter-0:
              ansible_host: "{{ hostvars['ntt-research-jupyter-0']['external_ip'] | default('ntt-research-jupyter-0') }}"
              jupyter_type: standalone

        jupyterhub_nodes:
          hosts:
            ntt-research-jupyterhub-0:
              ansible_host: "{{ hostvars['ntt-research-jupyterhub-0']['external_ip'] | default('ntt-research-jupyterhub-0') }}"
              jupyterhub_type: server

        pbs_cluster:
          hosts:
            ntt-research-hpc-pbs-0:
              ansible_host: "{{ hostvars['ntt-research-hpc-pbs-0']['external_ip'] | default('ntt-research-hpc-pbs-0') }}"
              pbs_role: server
            ntt-research-hpc-pbs-1:
              ansible_host: "{{ hostvars['ntt-research-hpc-pbs-1']['external_ip'] | default('ntt-research-hpc-pbs-1') }}"
              pbs_role: execution

        k8s_cluster:
          hosts:
            ntt-research-k8s-0:
              ansible_host: "{{ hostvars['ntt-research-k8s-0']['external_ip'] | default('ntt-research-k8s-0') }}"
              k8s_role: master
            ntt-research-k8s-1:
              ansible_host: "{{ hostvars['ntt-research-k8s-1']['external_ip'] | default('ntt-research-k8s-1') }}"
              k8s_role: worker
            ntt-research-k8s-2:
              ansible_host: "{{ hostvars['ntt-research-k8s-2']['external_ip'] | default('ntt-research-k8s-2') }}"
              k8s_role: worker

        vdi_nodes:
          hosts:
            ntt-research-vdi-0:
              ansible_host: "{{ hostvars['ntt-research-vdi-0']['external_ip'] | default('ntt-research-vdi-0') }}"
              vdi_type: windows

  vars:
    # Global variables
    ansible_user: "{{ ansible_ssh_user | default('ubuntu') }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_python_interpreter: /usr/bin/python3

    # Infrastructure variables
    project_id: "{{ lookup('env', 'GOOGLE_CLOUD_PROJECT') }}"
    region: us-central1
    zone: us-central1-a

    # NFS/Storage variables
    filestore_ip: "{{ lookup('env', 'FILESTORE_IP') | default('10.74.215.42') }}"
    nfs_share_name: ntt_storage
    nfs_mount_point: /shared

    # SLURM variables
    slurm_cluster_name: ntt-research-slurm
    munge_key_path: "{{ nfs_mount_point }}/slurm-config/munge.key"
    slurm_conf_path: "{{ nfs_mount_point }}/slurm-config/slurm.conf"
