---
v2:
  metadata:
    title: "Jupyter Connection"
  login:
    host: "ntt-research-jupyter-0"
  job:
    adapter: "linux_host"
    submit_host: "ntt-research-jupyter-0"
    ssh_hosts:
      - ntt-research-jupyter-0
    site_timeout: 7200
    debug: true
    singularity_bin: false
    strict_host_checking: false
    tmux_bin: /usr/bin/tmux
