---
# External links configuration
external_links:
  - title: "Jupyter Lab"
    description: "Access Jupyter Lab Server"
    icon: "fa://jupyter"
    url: "http://ntt-research-jupyter.c.ntt-research.internal:8888"
    new_tab: true

# OOD Configuration
ood_port: 8080
servername: ntt-research-ood-0
jupyter_url: http://ntt-research-jupyter-0:8888
